version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
